apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: gestao-estoque-mongodb
  name: vol-gestao-estoque-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gestao-estoque-mongodb
  name: gestao-estoque-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gestao-estoque-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: gestao-estoque-mongodb
    spec:
      containers:
        - image: mongo:8
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: gestao-estoque-mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          envFrom:
            - configMapRef:
                name: gestao-estoque-env
          volumeMounts:
            - mountPath: /data/db
              name: vol-gestao-estoque-mongodb
      restartPolicy: Always
      volumes:
        - name: vol-gestao-estoque-mongodb
          persistentVolumeClaim:
            claimName: vol-gestao-estoque-mongodb
---

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gestao-estoque-mongodb
  name: gestao-estoque-mongodb
spec:
  type: ClusterIP
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: gestao-estoque-mongodb
